# Dados para acessar o Git
GITLAB_URL: "https://git.com"
GITLAB_USER: "Seu Usuário"
GITLAB_EMAIL: "user@git.com"
GITLAB_TOKEN: "xxxxx-yyyyyyyyyyyyyyy_hhhh"

GITLAB_PROJETCTS:
  # - projeto1
  # - projeto2


# Banco de dados do Suap / postgress
ID_USER: "0000000"
DB_HOST: 127.0.0.1
DB_PORT: 5432
DB_DATABASE: suap_dev
DB_USERNAME: postgres
DB_PASSWORD: ""

# Dados para acessar o Google Calendário
GOOGLE_CALENDAR:
  CREDENTIALS_FILE: "inc/secret_credentials.json"
  SCOPES: ['https://www.googleapis.com/auth/calendar']
  API_NAME: "calendar"
  API_VERSION: "v3"

# Dados dos arquivo 
CALENDAR_ICS: "inc/calendar.ics"
DIR_ATIVIDADES: "atividades/"
DIR_CHAMADOS: "chamados/"
DIR_EVENTOS: "eventos/"



